version: "3.8"

services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - "3000:3000"
  # postgres:
  #   image: postgres:17
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
